/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#45464d',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'on-tertiary-container': '#98805d',
        'inverse-on-surface': '#eaf1ff',
        'primary-container': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'on-error': '#ffffff',
        'outline-variant': '#c6c6cd',
        'on-primary-fixed': '#131b2e',
        'inverse-primary': '#bec6e0',
        'primary-fixed-dim': '#bec6e0',
        'error-container': '#ffdad6',
        surface: '#f8f9ff',
        'inverse-surface': '#213145',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'on-secondary-container': '#fefcff',
        background: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'on-primary-container': '#7c839b',
        'on-secondary': '#ffffff',
        tertiary: '#000000',
        'tertiary-container': '#271901',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f8f9ff',
        'surface-container-high': '#dce9ff',
        error: '#ba1a1a',
        secondary: '#0058be',
        'on-secondary-fixed-variant': '#004395',
        'on-tertiary-fixed-variant': '#574425',
        primary: '#000000',
        outline: '#76777d',
        'tertiary-fixed': '#fcdeb5',
        'secondary-container': '#2170e4',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#271901',
        'on-secondary-fixed': '#001a42',
        'surface-container': '#e5eeff',
        'secondary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#dec29a',
        'on-error-container': '#93000a',
        'primary-fixed': '#dae2fd',
        'surface-container-low': '#eff4ff',
        'secondary-fixed-dim': '#adc6ff',
        'surface-tint': '#565e74',
        'emerald-600': '#059669',
        'amber-500': '#f59e0b',
        'crimson-600': '#dc2626',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '64px',
        base: '8px',
        gutter: '24px',
        md: '24px',
        sm: '12px',
        xs: '4px',
        lg: '40px',
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'data-tabular': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'data-tabular': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
